import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased bg-zinc-100`}>
        <div className="container mx-auto my-4">
          {typeof window !== "undefined" ? { children } : children}
        </div>
      </body>
    </html>
  );
}
